apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sentryflow
  name: ai-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-engine
  template:
    metadata:
      labels:
        app: ai-engine
    spec:
      containers:
      - name: sentryflow
        image: 5gsec/sentryflow-ai-engine:v0.1
        ports:
        - name: ai-engine
          protocol: TCP
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-engine
  namespace: sentryflow
spec:
  selector:
    app: ai-engine
  ports:
  - name: sentryflow-ai-engine
    protocol: TCP
    port: 5000
    targetPort: 5000
