// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: sentryflow_metrics.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIClassifierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	API []string `protobuf:"bytes,1,rep,name=API,proto3" json:"API,omitempty"`
}

func (x *APIClassifierRequest) Reset() {
	*x = APIClassifierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sentryflow_metrics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIClassifierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIClassifierRequest) ProtoMessage() {}

func (x *APIClassifierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_metrics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIClassifierRequest.ProtoReflect.Descriptor instead.
func (*APIClassifierRequest) Descriptor() ([]byte, []int) {
	return file_sentryflow_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *APIClassifierRequest) GetAPI() []string {
	if x != nil {
		return x.API
	}
	return nil
}

type APIClassifierResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	APIs map[string]uint64 `protobuf:"bytes,1,rep,name=APIs,proto3" json:"APIs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *APIClassifierResponse) Reset() {
	*x = APIClassifierResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sentryflow_metrics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIClassifierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIClassifierResponse) ProtoMessage() {}

func (x *APIClassifierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_metrics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIClassifierResponse.ProtoReflect.Descriptor instead.
func (*APIClassifierResponse) Descriptor() ([]byte, []int) {
	return file_sentryflow_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *APIClassifierResponse) GetAPIs() map[string]uint64 {
	if x != nil {
		return x.APIs
	}
	return nil
}

var File_sentryflow_metrics_proto protoreflect.FileDescriptor

var file_sentryflow_metrics_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x22, 0x28, 0x0a, 0x14, 0x41, 0x50, 0x49, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x41, 0x50, 0x49, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x41, 0x50, 0x49, 0x22, 0x8f,
	0x01, 0x0a, 0x15, 0x41, 0x50, 0x49, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x04, 0x41, 0x50, 0x49, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x50, 0x49, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x50, 0x49, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x04, 0x41, 0x50, 0x49, 0x73, 0x1a, 0x37, 0x0a, 0x09, 0x41, 0x50, 0x49, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x32, 0x64, 0x0a, 0x0d, 0x41, 0x50, 0x49, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x12, 0x53, 0x0a, 0x0c, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x41, 0x50, 0x49,
	0x73, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x50, 0x49,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x50, 0x49,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x15, 0x5a, 0x13, 0x53, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x46, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sentryflow_metrics_proto_rawDescOnce sync.Once
	file_sentryflow_metrics_proto_rawDescData = file_sentryflow_metrics_proto_rawDesc
)

func file_sentryflow_metrics_proto_rawDescGZIP() []byte {
	file_sentryflow_metrics_proto_rawDescOnce.Do(func() {
		file_sentryflow_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(file_sentryflow_metrics_proto_rawDescData)
	})
	return file_sentryflow_metrics_proto_rawDescData
}

var file_sentryflow_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sentryflow_metrics_proto_goTypes = []interface{}{
	(*APIClassifierRequest)(nil),  // 0: protobuf.APIClassifierRequest
	(*APIClassifierResponse)(nil), // 1: protobuf.APIClassifierResponse
	nil,                           // 2: protobuf.APIClassifierResponse.APIsEntry
}
var file_sentryflow_metrics_proto_depIdxs = []int32{
	2, // 0: protobuf.APIClassifierResponse.APIs:type_name -> protobuf.APIClassifierResponse.APIsEntry
	0, // 1: protobuf.APIClassifier.ClassifyAPIs:input_type -> protobuf.APIClassifierRequest
	1, // 2: protobuf.APIClassifier.ClassifyAPIs:output_type -> protobuf.APIClassifierResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sentryflow_metrics_proto_init() }
func file_sentryflow_metrics_proto_init() {
	if File_sentryflow_metrics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sentryflow_metrics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIClassifierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sentryflow_metrics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIClassifierResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sentryflow_metrics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentryflow_metrics_proto_goTypes,
		DependencyIndexes: file_sentryflow_metrics_proto_depIdxs,
		MessageInfos:      file_sentryflow_metrics_proto_msgTypes,
	}.Build()
	File_sentryflow_metrics_proto = out.File
	file_sentryflow_metrics_proto_rawDesc = nil
	file_sentryflow_metrics_proto_goTypes = nil
	file_sentryflow_metrics_proto_depIdxs = nil
}
