# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/sentryflow_metrics.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!protobuf/sentryflow_metrics.proto\x12\x08protobuf\"(\n\x18\x41PIClassificationRequest\x12\x0c\n\x04path\x18\x01 \x03(\t\";\n\x19\x41PIClassificationResponse\x12\x0e\n\x06merged\x18\x01 \x01(\t\x12\x0e\n\x06\x66ields\x18\x02 \x03(\t2x\n\x11SentryFlowMetrics\x12\x63\n\x14GetAPIClassification\x12\".protobuf.APIClassificationRequest\x1a#.protobuf.APIClassificationResponse(\x01\x30\x01\x42\x15Z\x13SentryFlow/protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.sentryflow_metrics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023SentryFlow/protobuf'
  _globals['_APICLASSIFICATIONREQUEST']._serialized_start=47
  _globals['_APICLASSIFICATIONREQUEST']._serialized_end=87
  _globals['_APICLASSIFICATIONRESPONSE']._serialized_start=89
  _globals['_APICLASSIFICATIONRESPONSE']._serialized_end=148
  _globals['_SENTRYFLOWMETRICS']._serialized_start=150
  _globals['_SENTRYFLOWMETRICS']._serialized_end=270
# @@protoc_insertion_point(module_scope)
