// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: mylog.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogStoreClient is the client API for LogStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogStoreClient interface {
	SendMyLog(ctx context.Context, in *MyLog, opts ...grpc.CallOption) (*LogResponse, error)
}

type logStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewLogStoreClient(cc grpc.ClientConnInterface) LogStoreClient {
	return &logStoreClient{cc}
}

func (c *logStoreClient) SendMyLog(ctx context.Context, in *MyLog, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, "/common.LogStore/SendMyLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogStoreServer is the server API for LogStore service.
// All implementations must embed UnimplementedLogStoreServer
// for forward compatibility
type LogStoreServer interface {
	SendMyLog(context.Context, *MyLog) (*LogResponse, error)
	mustEmbedUnimplementedLogStoreServer()
}

// UnimplementedLogStoreServer must be embedded to have forward compatible implementations.
type UnimplementedLogStoreServer struct {
}

func (UnimplementedLogStoreServer) SendMyLog(context.Context, *MyLog) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMyLog not implemented")
}
func (UnimplementedLogStoreServer) mustEmbedUnimplementedLogStoreServer() {}

// UnsafeLogStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogStoreServer will
// result in compilation errors.
type UnsafeLogStoreServer interface {
	mustEmbedUnimplementedLogStoreServer()
}

func RegisterLogStoreServer(s grpc.ServiceRegistrar, srv LogStoreServer) {
	s.RegisterService(&LogStore_ServiceDesc, srv)
}

func _LogStore_SendMyLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogStoreServer).SendMyLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.LogStore/SendMyLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogStoreServer).SendMyLog(ctx, req.(*MyLog))
	}
	return interceptor(ctx, in, info, handler)
}

// LogStore_ServiceDesc is the grpc.ServiceDesc for LogStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.LogStore",
	HandlerType: (*LogStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMyLog",
			Handler:    _LogStore_SendMyLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mylog.proto",
}
