name: release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v1

    # - name: Login to DockerHub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get tag
      id: tag
      run: |
        if [ ${{ github.ref }} == "refs/heads/main" ]; then
          echo "tag=latest" >> $GITHUB_OUTPUT
        else
          echo "tag=tmp" >> $GITHUB_OUTPUT
        fi

    - name: Build SentryFlow Image
      working-directory: ./sentryflow
      run: |
         make TAG=${{ steps.tag.outputs.tag }} build-image

    # - name: Push SentryFlow Image
    #   run: |
    #      docker push 5gsec/sentryflow:${{ steps.tag.outputs.tag }}

    - name: Build SentryFlow AI Engine Image
      working-directory: ./ai-engine
      run: |
         make TAG=${{ steps.tag.outputs.tag }} build-image

    # - name: Push SentryFlow AI Engine Image
    #   run: |
    #      docker push 5gsec/sentryflow-ai-engine:${{ steps.tag.outputs.tag }}
